SmartMaskDetector/SmartMaskDetector/urls.py
from django.contrib import admin
from django.urls import path, include
from check_mask import views

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', views.home,name="home"),
    path('check_mask/',include('check_mask.urls')),
]

SmartMaskDetector/check_mask/urls.py
from django.contrib import admin
from django.urls import path,include
from check_mask import views

app_name='check_mask'

urlpatterns = [
    path('webcam', views.webcam,name="webcam"),
    path('mail', views.send_mail,name="send_mail"),
    path('video_feed', views.video_feed, name='video_feed'),
]

SmartMaskDetector/check_mask/views.py
from django.shortcuts import render, redirect
from django.http.response import StreamingHttpResponse
from mask_detector.camera import WebCam
from email.mime.text import MIMEText
from email.utils import formataddr
from email.mime.multipart import MIMEMultipart  
from email.mime.base import MIMEBase
from email import encoders  
import pyautogui 
import smtplib
import ssl

def home(request):    
    return render(request,'home.html')

def webcam(request):
    return render(request,'webcam.html')

def send_mail(request):
    myScreenshot = pyautogui.screenshot()
    myScreenshot.save(r'E:/Ujala_folder/sem 6/ml/Sem6_FD/SmartMaskDetector/dataset/ss.png')
   
    sender_email = 'anchallsm2000@gmail.com'
    sender_name = 'Anchal Maurya'
    password = 'frjbzdqbkadzhupv'
    receiver_email = 'ujalamaurya.um@gmail.com'
    receiver_name = 'Ujala Maurya'
    body = """\
        <html>
          <body bgcolor=blue>
            <h3>Hello """ + receiver_name + """,<h3>
            <br>
            <h4>This email has been sent to you to inform that the 
            following person in screenshot is not wearing mask.<h4>
            <br>
          </body>
        </html>
        """
    filename = 'E:/Ujala_folder/sem 6/ml/Sem6_FD/SmartMaskDetector/dataset/ss.png'
    msg = MIMEMultipart()
    msg['To'] = formataddr((receiver_name, receiver_email))
    msg['From'] = formataddr((sender_name, sender_email))
    msg['Subject'] = 'Regarding No Mask'
    msg.attach(MIMEText(body,'html', 'utf-8'))
    try:
        with open(filename, "rb") as attachment:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())

        encoders.encode_base64(part)
        part.add_header(
                        "Content-Disposition",
                        f"attachment; filename= {filename}",
                )
        msg.attach(part)
        
    except Exception as e:
            print(f'Oh no! We didnt found the attachment!n{e}')
           
    try:
            server = smtplib.SMTP('smtp.gmail.com', 587)
            context = ssl.create_default_context()
            server.starttls(context=context)
            server.login(sender_email, password)
            server.sendmail(sender_email, receiver_email, msg.as_string())
            
    except Exception as e:
            print(f'Oh no! Something bad happened!n{e}')
            
    finally:
            server.quit()
    
    return redirect('home')

def gen(camera):
	while True:
		frame = camera.get_frame()
		yield (b'--frame\r\n'
				b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

def video_feed(request):
	return StreamingHttpResponse(gen(WebCam()),
					content_type='multipart/x-mixed-replace; boundary=frame')

SmartMaskDetector/check_mask/templates/home.html
{% load static %}  
<!DOCTYPE html>
<html>
  <head>
      <title>Mask Detector </title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- favicon file -->
      <link rel=" shortcut icon" href="/static/logo.png" type="image/png"> 
      <!-- Bootstrap -->
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block css %}    {% endblock %}

      <link rel="stylesheet" href="/static/style.css?{% now 'U' %}">
     
  </head>

  <body>

    {% block webcam %}
      <div class="container-fluid">
        <div class="container">
		
           
            <h1>Smart Mask Detector</h1><br>
            <p>
              This project helps the authorities to make the process of monitoring fast. The project helps us to spread awareness 
              among people using face mask properly. It also detects if, the person is using a handkerchief or hand instead of a 
              face mask for covering the face and it will classify it as without mask.
            </p>
            <a class="btn btn-primary" href="{% url 'check_mask:webcam' %}">Start Detecting --></a>
        </div>
		
      </div>
    
	{% endblock %}
        
  </body>
</html>

SmartMaskDetector/check_mask/templates/sendmail.html
{% extends 'home.html' %}
{% load static %}
    {% block css %}
	<style>
	body{
		background-color: black;
		color: white;
	}
	</style>
    {% endblock %}

	{% block webcam %}
    <div class="container">
	<div class="row">
		<form action="" method="post">
                {% csrf_token %}        
                <input type="password" name="password"></input>
				<button class="btn btn-primary" type="submit">send mail</button>
        </form> 
	</div>
	</div>
	{% endblock %}

SmartMaskDetector/check_mask/templates/webcam.html
{% extends 'home.html' %}
{% load static %}
    {% block css %}
	<style>
	body{
		background-color: black;
		color: white;
	}
	</style>
    {% endblock %}

	{% block webcam %}
    <div class="container">
	<div class="row">
		<div class="col-lg-9 col-md-10"><br>
			<h1>Live Video Streaming</h1>	  
			<img id="videofeed" src = "{% url 'check_mask:video_feed' %}">
		</div>
	  
		<div class="col-lg-3 col-md-4">
		<br><br>
			<h3>Instruction:</h3>
			<p>1. Keep your face properly<p>
			<p>2. Always wear mask</p>
			<p>3. Do not use handercheif</p>
			<p>4. DO not use hand also</p><br><br>
		
		<a class="btn btn-primary" href="{% url 'check_mask:send_mail' %}">send mail</a>
	
		</div>
	</div>
	</div>
	{% endblock %}